name: Lint

on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Install
        run: |
          npm ci
      - name: ESLint
        run: |
          npm run lint

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Install
        run: |
          npm ci
      - name: Prettier
        run: |
          npm run prettier
